### ISSUE TITLE
Just wanna say how peng this library is.

### ISSUE THREAD

**Issue by snwmc** [idrizp/commando#1]
Once taken place in a terribly dreadful time, there was a small cat-licking bird that lived on a not-so-big lane by my house whose name was Charles just like every other soul, male or female, that lived on my smelly, stinky, orange , old, rotten, messy, busted cul-de-sac between Belmont and Rose which are both awfully gay Streets Like North street or some shit that reminds me of a celebrity like Paris Hilton or some blonde loser that doesn't even know the capital of her own country, which is the United States of America aka: The U.S.A which is a pristine nation of beauty, opposing to a country as the country of Somalia and Belgium, a part of Europe, which doesn't even have a government, it's just in a complete state of anarchy just like my mind and soul which are both filled with outrageous nonsense that I'm typing down right now into some fat long sentence that probably makes no sense but who cares I'm trying to set some sort of weird record here like most ducks snorted or some weird thing like that and if I do set some sort of record I will be in the Guinness Book of chimkin nungets World Records (though anti-American and pro-European, a place of pitty and despair as Somalia is) which was always my dream because that book has a whole bunch a cool and weird stuff in it and I would Become famous and add to the weirdness of the book like some of their records which reminds me of the Rob & Big where Rob sets all of those skateboarding Records And Big Black eats bananas and donuts and three weeks later they both get plaques saying the record they set and I want to get one of those so that's why I'm writing all of this stuff down without ever using a period or some other sentence ending mark like an exclamation point or a question mark or any other symbol that could possibly end my streak of words that is really long now and would take me a while to count just like counting sheep which is supposed to put you to sleep but it really keeps you awake because you want to keep counting and counting until you don't know what comes after trillions, but that would take Years or something because it would take a while just to count a trillion seconds or minutes would be even worse just like how ducks are worse that geese because they are more aggressive around their young unlike great white sharks which are often eaten by their mothers when they are born and the ones who do make it out alive have no mother to teach them how to hunt or whatever because none of that matters because us human beings have mothers unless they die or run off with some CEO of a big company or someone else who makes a lot of money and then they leave you with your dad and you are jealous of your friends if you have any because they have moms and you don't because your mom was some greedy pig who wanted money but ended up only getting the money part and she bought drugs because she was depressed and ended up killing herself from an overdose and you wouldn't even know about it until you become some rich person and check the files somewhere and learn that she died of a overdose and you eyes get all teary and then you start crying because you know that you wouldn't be alive without that woman you called mom and I just found out right now that the longest sentence is like 10,000 words so I have a ways to go and you have to go with me so let's go to 6th gear and throw out some words like Emphysema which I had to do a report on in 4th grade because we had a ton of projects and this was the disease one and we chose diseases out of a hat and I came out with Emphysema which is a form of lung cancer which is 98% caused by smoking which reminds me of the way my dad describes smoking: "you get plant leaves, wrap them in paper, light it on fire and suck on it" which is normally a sentence but not today because I'm setting out on the quest for a long sentence that I'm typing up which reminds me of a story my grandpa told me about himself when he was "your age" about how they covered the letters on the type writers and they had to type so that they could memorize where the letters are on a type writer and my grandpa says he will never regret taking that class because it helped him out a lot when it came to typing and now a days he is not bad a typing at all because He is almost as fast as me because I am a pretty fast typer and writing this article isn't taking very long and expect being pretty far pretty soon at the pace I'm going right now so there are going to be some serious records getting busted when I'm finally finished writing this article on this dumb website which will probably end up huffing this article even though it is fun-packed and joyful and keeps the reader reading when they use that excuse to mom saying "just one more sentence" but that sentence is 10,000 words long and still continuing to go at a reasonable pace and it is going to shatter most of those long sentence records just like how the chargers are going to shatter the most consecutive years without a super bowl win record and I doubt that they will win one in the near future but they patriots are going to win some serious super bowls because they are the best team ever even better than the cowboys or 49ers and no one cares a bout them so go patriots and boo chargers even though I live in San Diego and Like the Padres I hate the Chargers because they are bad and the padres are bad too but I don't care because they are my favorite team and the dodgers are my least favorite along with the Yankees because the Yankees get a lot of money to spend and the padres and marlins get almost nothing and then the Yankees buy a-rod for a lot and the Rays get almost no money but are still fighting for first place this season without expensive players like Derek Jeter or a-rod or Johnny Damon or whoever because they are an all around better team that can beat the Yankees even though the Yankees can beat the royals a lot who really suck because they suck more that the padres do and so do the mariners and Rockies even thought the Rockies went to the world series last year they lost and haven't stopped losing for a while now, either and they are last place in the NL west and that is where the padres used to be but they started hitting home runs and winning games and are dong pretty good right now despite having little offense except for Adrian Gonzalez who is leading the NL in RBI's even though he is on the team who scores the least runs in the league but they are not last in homeruns though they are like 5 away or something but I’m not sure so screw that and let's talk about something fun like water or food or dirt or something but I think food is the best because their is a lot of things to talk about with food like you r favorite food which mine happens to be some spicy burrito form Chipotle mexican grill and it is very good just like this macaroni my mom made one time that had bread crumbs on top and it was very good like all of the food they serve on top chef which I wish I could be a judge for because they have a lot of good food on that show and it makes my mouth water whenever I watch it and that is why I watch it because the food is totally awesome and sometimes I hate the people but they end up getting eliminated like the Dance crews in France's Best Dance Crew which is a great show and you should watch it because people do good dancing like the JFrabbawockeez because they won the first season and they are very good just like supreme soul and So real crew and phresh select and super cr3w and I’m only at 1500 words right now so I have to write some serious stuff like a life biography about myself and anything I’ve ever done which includes going to big bear to ski, fishing, breathing, swimming, going, farting, eating, sleeping and a whole lot more stuff which reminds me of 4th grade again when my teacher was debating with the class whether "a lot" was one or two words and all of the kids including myself said one while the teacher said two and he was right and we were wrong but no one cared because we all had fun arguing about and I have fun arguing with my friends about football and not baseball because in baseball we all like the same team but in football I like the patriots and my friends like the chargers and the 49ers and the eagles and the saints but my team always woops their team's ass and they say that the patriots "cheat" and that's how they won even though the patriots just pwned their team and they suck and my team is good but we all agree when it comes to baseball because we all like the padres and we never really argue over anything in baseball which is my favorite sport and I play it and I am good a it and I want it to be my profession but I doubt that that will happen so my backup plan is being a cop because you get all of the benefits and you get paid after you retire which is good news and I would also like to be some government dude or something like that because they get the benefits too so it would be cool to work for the government which reminds me that my principal worked at the white house and taught the president email because he was the computer guy or something like that so h knows a whole bunch of computer crap like my dad and he is fat too so everyone makes fun of him and I think he huffs kittens too but I am not sure and about that and what the hell is up with all the noob and kitten huffing on this gay ass website like all of the things like "the writer may have been huffing kittens" and stuff like that it really annoys the hell out of me just like other things such as when people clip their finger nails it makes that weird noise that get me all crazy and I hate it just like how me friend hates the sound of chalk on a chalkboard which I find soothing and relaxing but he gets really annoyed and psyched out and he is also very pale-skinned and so is the rest of his family so it must have been some genetic thing like twins and clones and whole bunch of other confusing science crap that I learned a long time ago in 7th grade or something which was when we watched movies in class like UHF which has "Weird Al" Yankovic in it and it is very funny because "Weird Al" Yankovic has to save a TV station with a whole bunch of weird shows like wheel of fish and rauls wild kingdom with a whole bunch of cool animals like flamingos and turtles and stuff like that but who cares lets get to the meaty part of this article which is the part where I write the longest word known to man which is Methionylthreonylthreonyl...isoleucine which is cut out because it has 189,819 words so Wikipedia had to cut out the middle part and the longest word is the name of a protein which is the largest known to man to so big names go to big things is apparently the moral of this story ladies and gentleman the road doesn't stop here and I have to continue no matter what you say or think so I should just write some story now that has no periods so lets start with a guy named Carl who liked fish and women and he went to Clara’s house and they had a good food but that isn't enough of a story to set the record so I think I’ll just stick to writing random crap which really makes no sense at all and here is some random picture that shows a guy who has two legs and another guy who has three who is mocking the guy with two legs because he rips his flesh in disgust every night and you think about who would be dumb enough to rip their flesh instead of cut the ring off or something that doesn't involve entirely gruesome crap like that and I have another life after this one just like how cats have 9 lives I have three because I’m on my second one right now and it is great and you might think I’m a whole new person but you are thinking wrong it's just when I died I came back t life and next time I die I’ll come back to life again and then when I die I’ll be dead for sure which reminds me of Stephen king's book called pet sematary which is coo because people come back to life because there was a burial ground that bring people back to life if they are dead and that book is a great book and you should read it along with the Harry Potter series which has magic in it and it is cool too so don't shank yourself when you are cutting that meat for dinner or you might die of massive blood loss or might just need a band aid I mean that works too or you don't even need a band aid because I don't use them and I have never gotten and infection in my life so maybe I’m lucky or have an alligator immune system or something but I don't use band aids and I don't use Neosporin on my cuts so I’m some sort of miracle I guess but I’m wasting twenty minutes of my miracle life on this retard article that I just want the Guinness book of world records to see and go that is the longest thing ever and have me in their book so I’m striving towards that goal right now and I’m not stopping until I hit at least 3000 words and then I’ll do the construction thing and finish thing up tomorrow or sometime after now and I will be the author of the longest single sentence on the planet earth which will be a real accomplishment on my part so you can be real jealous right now because I am making history right in front of you and if you are still reading this I am truly impressed because this article must be getting really boring by now and maybe your not even reading this just scanning the article for periods which I’m afraid you will not find until the very end of this article which is a very, very, long way away and if you are a slow reader well sucks for you but now I have to use that construction thing and I will finish this and now I am back after a hard day at work but I’m still going now so get ready to rumble with this long thing called a sentence that is as long as Mt. Everest is tall and the Marinas Trench is deep and speaking of the ocean fish of all kinds live in the ocean such as puffer fish which are poisonous to eat if not prepared right and will make you die after and you ADMINS BETTER NOT DELETE THIS BECAUSE IT IS SOME RECORD and if you do delete it well I will have this saved and what will you do then you people who will want to delete this because you don't care about people trying to break records so don't delete this or I will boycott Uncyclopedia and will be very mad at you guys like how I am Mad at Tim for being so annoying just like Celebrities and loud people and people who don't brush their teeth which makes me think of killing myself except I wouldn't do that because I am some sort of miracle as you probably read before or not because you are tired of reading this jumble of words that are still making a grammatically correct sentence that is breaking records right now and I won't stop until you let me break some serious records like longest sentence and some other weird stuff that I might get an award for or something but I also want that Guinness record plaque that you get for setting a monster record like most consecutive noses picked with boogers in them or something completely obscure like that which is like a bunch of the articles on this website which are actually some times funny like how to solve a one by one by one Rubik’s cube which made me laugh pretty good and the star wars one is good too so never delete those two because they are funny unlike this article because this article is more boring than funny but who cares some retard might laugh at this bundle of crap and I think that I will put that crap tag on this article so people know that this article isn't really funny but that it is long and boring like Dances with Wolves and some other long movies that you actually fall asleep during which is hard for me to do so I tend not to nut I did when I watched Dances with Wolves because it was really boring like counting sheep to a trillion or some other large number that some little kid says he wishes he had that many dollars but he will never get that many dollars because there isn't even that many in circulation right now and if there was that would be some major inflation right there so don't think you can get that much money kid because then you would not be doing this country a favor which it desperately needs I might add so instead burn money instead of make it and lower inflation rates and do everyone a favor except for the people who are already really rich and don't care about inflation and would rather drive an escalade instead of a Prius in times like this with all of the gas prices and stuff that would drive up your bill but they don't notice because they have a lot of money and don't care therefore they should die and burn in hell with all of the lawyers and other bad people on this ball we call earth that really isn't a perfect sphere because of the mountains and valleys makes it look all jagged but from space it looks like a sphere but looks may be deceiving so don't think that the world is a sphere no matter what other people say and tell them to eat themselves when they try to convince you that the earth is really a sphere but it isn't just like how most ignorant people think that Columbus found America but he really didn't that was Leif Erickson, but Columbus really found the Bahamas thinking they were penis outside of china and he was wrong so everyone forget Columbus and remember some other sailor like Henry Hudson who tried to find the northern passage but didn't so his crew killed him but a he was a great man any way so remember him instead of Columbus or remember William Penn who created Pennsylvania or remember your grandma or someone but not Columbus so go ahead and think that the earth is flat even though it isn't and it can have for corners if you think about it so go die and fall off a cliff or something interesting like that or at least get a life that want’ to penis e a cool record like the one I'm setting right now so go to a pawnshop and buy a life or kill yourself and get a new one or something weird like that or I will force you to and if you are still reading this you are an amazing human because I forget most of the stuff I’ve written already except for the great white shark thing at the beginning of the article and I remember that I need to go see some good movies tomorrow or sometime in the near future like within a week or something but forget that I'm only at 3500 words now so lets go to 4000 penis and then maybe I’ll call it quits because this is boring and I would rather write another article that is good and long but not all one sentence like this one so let's come up with some final five hundred words or so to say before I stop writing all of the nonsense so let's brainstorm ideas like poo, ducks, lemons, flanges, more ducks and star wars which sound about like enough and I like star wars out of there so let's talk about some penis star wars stuff like Kit Fisto who has weird tentacle things on his head and Ki-Adi-Mundi who has two brains and is on the Jedi which is penis honor and privilege because it is and Kit Fisto gets killed by Palpatine in the 3rd movie like Mace Windu who is cool and I like his light saber because it is purple unlike the standard blue and green colors which I prefer green out of but most people seem to like the blue colors but who cares about them they like blue and green is better so you better not like blue or you are some lame person that will be lame for the rest of your life like some people who think that they are cool but are really posers and they live their life not knowing that they are continually mocked and made fun of all of the time behind their backs and that they are really dumb or something so go out and tell all of the posers you know to not be posers anymore and tell them that they should go jump in a lake or something insulting like that and make them run and cry and you can laugh at them and hope they don't tell their mom who will be mad at you so maybe you shouldn't even do that you should just laugh at them behind their backs while they live the poser life and I'm near 4000 words now so let me slow down now yeah I have about a hundred words left so let me write down the exact amount before I stop writing so let me finish this thing up by talking about donuts and their fried goodness and how they make you fat and stuff but they do taste good so you should eat them because they are good and they taste good even though you could get fat but no one cares so eat them and be happy and I am starting to near 4000 now so just be a bit patient and this has been fun guys so let me finish right about, where you should wait for it, and wait, 'till right about, where we are almost there, having just two more for that you should wait, while this actually isn’t going to stop because I want this to keep going for a little while longer so that I can still break some record but man am I tired so I think I will actually shut up now, nope this has to continue forever and will continue for years and then a Bert killed the 3-legged guy and ate his orange while pooping and then I shall say the bird's name is "a bird who walked across the street killed a guy with a Minecraft nose and stuff. Jesus Christ is my lord and savior.You guys probably think that that is the worlds longest sentence, but it's not,because I just keep on adding commas, and it's pretty easy, if you think about it, so anyway there is this girl at school and she's my friend, and all but she's turning really mean, its a different person, and I'm trying to beat the record, but that girl, who likes this boy, who likes this girl, and who likes this other boy, and that same kid likes this other girl, but that girl like another guy, but the guy is actually a 40 year old man that eats penis for a living for the ability to never show the meerkats who's doing the write things oh and my last remark is that socialism does not work because look at Europe and Greece which is failing miserably; America always wins, there is no doubt about America's beauty, Amen and I just made it longer, and longer still as I continue to talk and talk and talk and talk throughout this, though I believe it would be referred to more as typing, so I will continue to type and type and type and type and type until I grow bored of it, and I have so I will take my leave soon, but not before I say that I somehow managed to make this already super long sentence longer, so HALLELUJAH, but we are not done yet everything I just said IS NOT RELEVANT to daily life, if you read this all you have no life, did u mention I like waffles and pancakes and people and gay marriage. This is a hell of a sentence peeps. What ever the man did the child would not wake up from the bullet that entered his head and he woke up again to find himself in heaven and then he felt fire and it was hot very hot very hot very hot very hot very hot but then he said "so" and he was alive again, alive, alive, alive, alive and then he flew like a bird and he looked in the mirror and saw his wings and his beak and his legs he was a bird like wow like what like wow like what that's so cool but then a dragon came and saved the bird and turned him into a princess and he had to live with the dragons and it was so boring and like who wrote this, who has the time to do this, because I obviously don't, and many other people don't, such as the president, CEO's of companies, terrorists, workers, kids, parents, adults, and many other people, but who even gives a fuck about what we're doing, because this is all bullshit. yeet yeet ass haircut goobly gooobly spongebob asspants

**Comment by idrizp** [comment]
Thanks. I'll look into it.

**Comment by imbreydan** [comment]
I also agree. This library is absolutely so very peng. 🙌😎

**Comment by imbreydan** [comment]
![noted](https://user-images.githubusercontent.com/47508887/120021517-27a65800-bfb9-11eb-8768-a74461f6ab9d.JPG)

**Comment by idrizp** [comment]
Upon further inspection, this issue is ALREADY solved. 🎉
